//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccountMenuOptions {
            get {
                return ResourceManager.GetString("AccountMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^\d{0,14}(.\d{2})?$&quot;.
        /// </summary>
        internal static string AmountRegex {
            get {
                return ResourceManager.GetString("AmountRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username for your new account..
        /// </summary>
        internal static string CreateUsername {
            get {
                return ResourceManager.GetString("CreateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username to login..
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to [login] to an existing account, [register] for a new account], or [exit]?.
        /// </summary>
        internal static string ExistingAccountOrRegister {
            get {
                return ResourceManager.GetString("ExistingAccountOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for banking with Console First. Goodbye..
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to increase the amount of your loan, please speak to a store associate..
        /// </summary>
        internal static string LoanWithdraw {
            get {
                return ResourceManager.GetString("LoanWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to [view] an account, open a [new] account, or [exit]?.
        /// </summary>
        internal static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter: .
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. This service is temporarily unavailable..
        /// </summary>
        internal static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds in a term deposit account cannot be withdrawn before maturity except under specific conditions specified in your account agreement. Please speak to a store associate for details..
        /// </summary>
        internal static string TermDepositWithdraw {
            get {
                return ResourceManager.GetString("TermDepositWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is taken. Please enter another username..
        /// </summary>
        internal static string UsernameUnavailable {
            get {
                return ResourceManager.GetString("UsernameUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account matches that username..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid dollar amount..
        /// </summary>
        internal static string ValidAmount {
            get {
                return ResourceManager.GetString("ValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Console First Bank - banking the way it used to be..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of account would you like to open?.
        /// </summary>
        internal static string WhatAccountType {
            get {
                return ResourceManager.GetString("WhatAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the size of the certificate deposit term account requested?.
        /// </summary>
        internal static string WhatSizeCD {
            get {
                return ResourceManager.GetString("WhatSizeCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the size of the loan you would like to take out? All loans subject to approval..
        /// </summary>
        internal static string WhatSizeLoan {
            get {
                return ResourceManager.GetString("WhatSizeLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds could not be transferred from the account provided..
        /// </summary>
        internal static string WithdrawalFailed {
            get {
                return ResourceManager.GetString("WithdrawalFailed", resourceCulture);
            }
        }
    }
}
